### ISSUE TITLE
关于 MINE-H5-UI 2.0 的展望

### ISSUE THREAD

**Issue by biaov** [biaov/MINE-H5-UI#2]
## 特征
* 基于 Vue3.x。
* 使用 npm + vite 的工作流，支持 ES6+。
* 全面使用 TypeScript + Composition-API 来重构 UI 组件库。

## 技术栈

> HTML5 + CSS3+ Less + ES6<sup>+</sup> + Vue3.x ( Composition-api ) + TypeScript  + Vite + Gulp + Rollup + Jest

## 预估发布时间
* 时间就像海绵，挤挤还是会有的，已有计划，按照计划前进着。
* 每次挤一挤，每次写一点，持续时间可能有点久。
* 具体时间看心情 😆
## 已完成
* `mine-h5-ui v2.x` 已完成

**Comment by biaov** [comment]
已发布

**Comment by biaov** [comment]
## 关于支持新 vue 语法的计划
* 将 `mine-h5-ui v2.x` 支持 vue 新语法糖
* 更新时间待定

**Comment by Gavin-yh** [comment]
> ## 关于支持新 vue 语法的计划
> * 将 `mine-h5-ui v2.x` 支持 vue 新语法糖
> * 更新时间待定

啥时候重构呢

**Comment by biaov** [comment]
已经在重构了，不过时间有点久




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 中午11:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [biaov/MINE-H5-UI] 关于 MINE-H5-UI 2.0 的展望 (#2)





  
关于支持新 vue 语法的计划
  
将 mine-h5-ui v2.x 支持 vue 新语法糖
 
更新时间待定
   
啥时候重构呢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Gavin-yh** [comment]
> 已经在重构了，不过时间有点久

可以参与吗

**Comment by Gavin-yh** [comment]
> 已经在重构了，不过时间有点久

可以参与吗，目前公司内部也在开发一套组件库

**Comment by biaov** [comment]
首先欢迎，但是这个只是个人的兴趣爱好，没有很多的技术含量，而且里面的代码风格和代码规范挺麻烦的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 中午11:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [biaov/MINE-H5-UI] 关于 MINE-H5-UI 2.0 的展望 (#2)





  
已经在重构了，不过时间有点久
  
可以参与吗，目前公司内部也在开发一套组件库
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
