### ISSUE TITLE
vue3版本3.2.26引入组件报错

### ISSUE THREAD

**Issue by sllsusan** [biaov/MINE-H5-UI#22]
error: No matching export in "node_modules/mine-h5-ui/node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "useContext"

**Comment by biaov** [comment]
### 原因

- `^vue3.1.x` 版本不支持

### 解决

- 方法一（推荐）
  - 严格按照 package-lock.json 安装依赖
- 方法二
  - 手动降低 vue 版本至 3.0.x
- 方法三（不推荐）
  - 等待作者后续升级项目到 vue 最新版支持的版本

**Comment by biaov** [comment]
> error: No matching export in "node_modules/mine-h5-ui/node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "useContext"

### 原因

- `^vue3.1.x` 版本不支持

### 解决

- 方法一（推荐）
  - 严格按照 package-lock.json 安装依赖
- 方法二
  - 手动降低 vue 版本至 3.0.x
- 方法三（不推荐）
  - 等待作者后续升级项目到 vue 最新版支持的版本

**Comment by sllsusan** [comment]
![image](https://user-images.githubusercontent.com/32158521/146698476-a6c71467-f113-4392-a1bb-42ae03d71b28.png)
降低 vue 版本至 3.0.x后报错更多了。。。

**Comment by biaov** [comment]
git ***@***.***:biaov/MINE-H5-UI.git




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月20日(星期一) 上午9:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [biaov/MINE-H5-UI] vue3版本3.2.26引入组件报错 (Issue #22)





 

 降低 vue 版本至 3.0.x后报错更多了。。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
