### ISSUE TITLE
drag 不用语法糖请问该怎么写？

### ISSUE THREAD

**Issue by timosss** [biaov/MINE-H5-UI#25]
v-model:current="current" 这个参数就是不是当前点击控件的的DOM ref?
![c630c00cb6bac44b16f727c0d4e67c9](https://user-images.githubusercontent.com/27383568/169561833-1cd076f0-0dc5-45d9-b5ba-bddc7ae4aed4.png)

**Comment by biaov** [comment]
不是，current 表示当前你选中的 list 的索引，没有选中则返回 -1

**Comment by biaov** [comment]
> v-model:current="current" 这个参数就是不是当前点击控件的的DOM ref? ![c630c00cb6bac44b16f727c0d4e67c9](https://user-images.githubusercontent.com/27383568/169561833-1cd076f0-0dc5-45d9-b5ba-bddc7ae4aed4.png)

不是，current 表示当前你选中的 list 的索引，没有选中则返回 -1
