### ISSUE TITLE
按需引入也会全部都打包

### ISSUE THREAD

**Issue by Tyh2001** [biaov/MINE-H5-UI#28]
```ts
import { createApp } from 'vue'
import App from './App.vue';

import { MeButton } from 'mine-h5-ui'
import 'mine-h5-ui/lib/theme-default/index.css'

console.log(MeButton)

createApp(App)
  .use(MeButton)
  .mount('#app')
```

这样按需引入最终也会将所有的组件都打包进去了

**Comment by Tyh2001** [comment]
解决方式可参考：https://github.com/FightingDesign/fighting-design/blob/master/packages/fighting-design/index.ts

**Comment by biaov** [comment]
> 解决方式可参考：https://github.com/FightingDesign/fighting-design/blob/master/packages/fighting-design/index.ts

感谢大佬，已经处理更新
更新版本 [mine-h5-ui v2.3.7](https://www.npmjs.com/package/mine-h5-ui/v/2.3.7)

**Comment by biaov** [comment]
加过了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 上午9:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [biaov/MINE-H5-UI] 按需引入也会全部都打包 (Issue #28)





 hello，加个微信吗？ 
 https://github.com/Tyh2001 
 首页可加 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "biaov/MINE-H5-UI"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年9月15日(星期四) 上午9:46 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [biaov/MINE-H5-UI] 按需引入也会全部都打包 (Issue #28) 
 
 
 
 
 
   
 Closed #28 as completed.
