### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by zgsgs** [biaov/MINE-H5-UI#29]
![image](https://user-images.githubusercontent.com/22882957/198558546-8a00db65-0b83-419a-a604-d4396b341a0a.png)

**Comment by biaov** [comment]
> ![图片](https://user-images.githubusercontent.com/22882957/198558546-8a00db65-0b83-419a-a604-d4396b341a0a.png)
这个是由于rollup-plugin-typescript2不支持部分vue3的兼容问题，不会影响实际开发
