### ISSUE TITLE
这是一个请教问题

### ISSUE THREAD

**Issue by azhen98** [biaov/MINE-H5-UI#31]
···js

  "name": "hex-datepicker",
  "private": false,
  "version": "0.1.8",
  "style": "./dist/style.css",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
···

这里面的 style 字段是用来干什么的呢，我自己编写的组件打包完成之后，在项目里面导入会提醒我没有 export  css，是不是需要配置这个字段呢？

**Comment by biaov** [comment]
> ···js
> 
> "name": "hex-datepicker", "private": false, "version": "0.1.8", "style": "./dist/style.css", "scripts": { "dev": "vite", "build": "vue-tsc && vite build", "preview": "vite preview" }, ···
> 
> 这里面的 style 字段是用来干什么的呢，我自己编写的组件打包完成之后，在项目里面导入会提醒我没有 export css，是不是需要配置这个字段呢？

和 style 字段没有关系，看下是否配置了 exports 字段， exports 上没有配置 css 导出

**Comment by azhen98** [comment]
![image](https://user-images.githubusercontent.com/52627267/210937065-1d311fd3-1f34-46f8-a260-2a7ed0e9bb13.png)
是这样配置的吗？ 这个main 就是style文件

**Comment by biaov** [comment]
> ![image](https://user-images.githubusercontent.com/52627267/210937065-1d311fd3-1f34-46f8-a260-2a7ed0e9bb13.png) 是这样配置的吗？ 这个main 就是style文件

可以

**Comment by azhen98** [comment]
谢谢, 上面的 export 字段还是没有生效, 最终使用  element plus 的 css 方式
在 css.ts 里面导入相应的 css 文件

**Comment by biaov** [comment]
> 谢谢, 上面的 export 字段还是没有生效, 最终使用 element plus 的 css 方式 在 css.ts 里面导入相应的 css 文件

可以试一下，css导出具体的文件要带上.css后缀的，比如：
"./style": "./dist/main.css"

**Comment by azhen98** [comment]
大佬有没有遇到过 rollup 打包的时候 没有生成js文件， 只生成了 声明的 .d.ts 文件；有的ts文件其他地方没有依赖与它，打包的时候是不是会不生成，但是声明文件的确是生成了 
![image](https://user-images.githubusercontent.com/52627267/212459971-63b9de4c-f7bd-4856-9a42-7c9fa49a9121.png)
生成的文件
![image](https://user-images.githubusercontent.com/52627267/212459982-80b73e2b-d814-4ea9-bf71-4d94ccf54513.png)
style内部的代码
```js
import '../../theme-default/Datepicker.scss'
import 'element-plus/es/components/tab-pane/style/css'
import 'element-plus/es/components/tabs/style/css'
import 'element-plus/es/components/icon/style/css'
```

**Comment by azhen98** [comment]
如果开启 preservemodules 好像就会默认开启摇树

**Comment by biaov** [comment]
> 如果开启 preservemodules 好像就会默认开启摇树

rollup打包一般根据入口文件，然后打包成一个文件（且只会输出一个文件），我这里用的 `rollup-plugin-typescript2` 使其生成 `.d.ts` 文件，如果要生成每个 js 文件，则需要开启 `preservemodules` (保留模块)，至于你不想开启摇树，则需要看下配置或者换种方式打包，比如 `vite 打包` 等，这个我没有深入去了解过。

**Comment by azhen98** [comment]
![image](https://user-images.githubusercontent.com/52627267/212520893-f9b48ba6-6121-4059-a3a5-c4a70bf0fcbd.png)
图中 ts 文件夹里面有三个文件, 其中 index.ts 是入口, index2 被导入到了 index.ts, index3 在打包的时候会被过滤掉, 如果不在 index 导入index3 有什么办法能在打包的时候保留index3吗
preservemodules  这个配置项也开启了, 是不是说 如果某个文件没有被其他文件导入或者依赖都会被 roullp 过滤掉?
```JS
export default {
  input: `${input}/index.ts`,
  plugins: [
    clear({ targets: ['dist'] }),
    // vue(),
    typescript({
      useTsconfigDeclarationDir: false,
      abortOnError: false,
      clean: true,
      tsconfigOverride: {
        include: ['packages/**/*'],
      },
    })
  ],
  // treeshake: {
  //   moduleSideEffects: false
  // },
  output: {
    dir: `${output}/es`,
    format: "es",
    preserveModules: true,
  }
}
```

**Comment by biaov** [comment]
> 

会被过滤掉，因为没有入口，识别不到

**Comment by biaov** [comment]
> ![image](https://user-images.githubusercontent.com/52627267/212520893-f9b48ba6-6121-4059-a3a5-c4a70bf0fcbd.png) 图中 ts 文件夹里面有三个文件, 其中 index.ts 是入口, index2 被导入到了 index.ts, index3 在打包的时候会被过滤掉, 如果不在 index 导入index3 有什么办法能在打包的时候保留index3吗 preservemodules 这个配置项也开启了, 是不是说 如果某个文件没有被其他文件导入或者依赖都会被 roullp 过滤掉?
> 
> ```js
> export default {
>   input: `${input}/index.ts`,
>   plugins: [
>     clear({ targets: ['dist'] }),
>     // vue(),
>     typescript({
>       useTsconfigDeclarationDir: false,
>       abortOnError: false,
>       clean: true,
>       tsconfigOverride: {
>         include: ['packages/**/*'],
>       },
>     })
>   ],
>   // treeshake: {
>   //   moduleSideEffects: false
>   // },
>   output: {
>     dir: `${output}/es`,
>     format: "es",
>     preserveModules: true,
>   }
> }
> ```

会被过滤掉，因为没有入口，识别不到
