### ISSUE TITLE
Drag控件使用

### ISSUE THREAD

**Issue by LiuYimin** [biaov/mine-h5-ui#46]
最新版TS的,Drag按案例引入,报了个错"类型“ListDataItem”上不存在属性“url”。ts(2339)"
好像不影响使用,但是有个红线在那摆着.
<img width="522" alt="截屏2023-07-04 12 58 18" src="https://github.com/biaov/mine-h5-ui/assets/11698318/34b6ec3e-1e9a-4278-a6ae-5ff02a529b37">

**Comment by biaov** [comment]
> 最新版TS的,Drag按案例引入,报了个错"类型“ListDataItem”上不存在属性“url”。ts(2339)" 好像不影响使用,但是有个红线在那摆着. <img alt="截屏2023-07-04 12 58 18" width="522" src="https://user-images.githubusercontent.com/11698318/250758352-34b6ec3e-1e9a-4278-a6ae-5ff02a529b37.png">

修复中...
